export const reviews1 = `
{rid: "1234", by: "Bill Gates", "blurb":"On the surface it’s about math, but it’s really about how much math plays into our daily lives without our even knowing it.",https://www.gatesnotes.com/Books/How-Not-to-be-Wrong"}
`

export const reviews 2 =  `
{"item_id":"d5a39123-a66f-43db-bb7a-871464c5e9d1","by":"Bill Gates","rating":"","blurb":"Educated is even better than you’ve heard.\nMelinda and I loved Tara Westover’s journey from the mountains of Idaho to the halls of Cambridge.\n...\nEducated is an amazing story, and I get why it’s spent so much time on the top of the New York Times bestseller list. \n...\nTara is never cruel, even when she’s writing about some of her father’s most fringe beliefs.\n...\nI found it fascinating how it took studying philosophy and history in school for Tara to trust her own perception of the world.\n...\nAlthough it’s not a political book, Educated touches on a number of the divides in our country: red states versus blue states, rural versus urban, college-educated versus not. \n...\nTara’s process of self-discovery is beautifully captured in Educated. It’s the kind of book that I think everyone will enjoy, no matter what genre you usually pick up. She’s a talented writer, and I suspect this book isn’t the last we’ll hear from her.","url":"https://www.gatesnotes.com/Books/Educated"}
{"item_id":"703ec80c-c9ae-4e53-bc8b-d5ca06faa7c7","by":"Bill Gates","rating":"","blurb":"I couldn’t put down this thriller with a tragic ending.\nThe inside story of the Theranos scandal is almost too wild to believe.\n...\nThe public didn’t know about Theranos’ deception until Carreyrou broke the story as a reporter at the Wall Street Journal. Because he was so integral to the company’s demise, Bad Blood offers a remarkable inside look.\n\nSome of the details he shares are—for lack of a better word—insane.\n...\nBad Blood is also a cautionary tale about the virtues of celebrity. On the surface, Holmes was everything Silicon Valley loves in a CEO: charismatic and convincing with a memorable personal story made for magazine profiles.\n...\nBad Blood tackles some serious ethical questions, but it is ultimately a thriller with a tragic ending. It’s a fun read full of bizarre details that will make you gasp out loud. The story almost feels too ridiculous to be real at points (no wonder Hollywood is already planning to turn it into a movie). I think it’s the perfect book to read by the fire this winter.","url":"https://www.gatesnotes.com/Books/Bad-Blood"}
{"item_id":"1357cc95-e8e7-41ae-8897-7bca708560b6","by":"Matthew McConaughey","rating":"","blurb":"The most instrumental piece of literature and motivation I’ve ever read for me in my life.","url":"https://tim.blog/2020/10/19/matthew-mcconaughey/"}
{"item_id":"90d09172-6511-4ba2-9bd7-b12261c51789","by":"Naval Ravikant","rating":"","blurb":"\"One of my all time favorite books. I quote it all the time.\" - Naval Ravikant","url":"https://twitter.com/naval/status/693967197924790272?s=20"}
{"item_id":"cfa6f3d7-1632-404a-9b1a-080e31e5944a","by":"Naval Ravikant","rating":"","blurb":"Naval Ravikant's answer to \"any good book about economy for a beginner?\"","url":"https://twitter.com/naval/status/1156882081663737856?s=20"}
{"item_id":"1aca93c8-3532-42c2-a706-994025d78118","by":"Naval Ravikant","rating":"","blurb":"\"I love [this book].\" - Naval Ravikant","url":"https://twitter.com/naval/status/1190461054574137344?s=20"}
{"item_id":"8bf0cdf9-e963-4270-b9fa-b2e9f93f0b46","by":"Naval Ravikant","rating":"","blurb":"\"Fundamental and had a lot to teach.\" - Naval Ravikant","url":"https://twitter.com/naval/status/800431638261837824?s=20"}
{"item_id":"77acce13-cffd-4907-81f7-f34895e21c12","by":"Naval Ravikant","rating":"","blurb":"\"Fine book but it didn’t need to be an entire book. A blog post would have gotten the point across.\" - Naval Ravikant","url":"https://twitter.com/naval/status/974109608405970944?s=20"}
{"item_id":"7d1f77ab-ca80-4457-b5a6-097ff6deba6a","by":"Naval Ravikant","rating":"","blurb":"Naval Ravikant tweeted about this book.","url":"https://twitter.com/naval/status/1157887058582503424?s=20"}
{"item_id":"66471fc2-5aae-4281-9ab3-86f85baebf96","by":"Naval Ravikant","rating":"","blurb":"\"[The author] is doing the behind the scenes work to support entrepreneurship in America.\" - Naval Ravikant","url":"https://twitter.com/naval/status/718989721808941056?s=20"}
{"item_id":"28170254-f2f7-41a0-b077-569034e9eb27","by":"Naval Ravikant","rating":"","blurb":"\"That’s what I read [by Seneca].\" - Naval Ravikant","url":"https://twitter.com/naval/status/980930482111000576?s=20"}
{"item_id":"e6a4ad6f-d1f9-4657-b8c8-492521084574","by":"Naval Ravikant","rating":"","blurb":"\"A beautiful book.\" - Naval Ravikant","url":"https://twitter.com/naval/status/699274280077365248?s=20"}
{"item_id":"2b2c6b65-a318-46da-9a21-fc12d462833a","by":"Naval Ravikant","rating":"","blurb":"\"Great series.\" - Naval Ravikant","url":"https://twitter.com/naval/status/980972194871238657?s=20"}
{"item_id":"1d250c4c-e6e7-45b6-9467-35a760fc39c5","by":"Naval Ravikant","rating":"","blurb":"\"Good books are worth re-reading. Great books are worth re-buying.\" - Naval Ravikant","url":"https://twitter.com/naval/status/1142485738061099008?s=20"}
{"item_id":"516f06ab-4147-4737-9020-4383a631e232","by":"Naval Ravikant","rating":"","blurb":"Naval Ravikant mentioned this book on \"The Tim Ferriss Show\" podcast.","url":"https://tim.blog/naval-ravikant-on-the-tim-ferriss-show-transcript/"}
{"item_id":"6e123b75-c365-4733-b7bb-aef765d0b1c8","by":"Naval Ravikant","rating":"","blurb":"Naval Ravikant tweeted about this book.","url":"https://twitter.com/naval/status/24581077419?s=20"}
{"item_id":"7571b57e-31ac-4032-81ff-afc42f2bc7ca","by":"Naval Ravikant","rating":"","blurb":"Naval Ravikant tweeted about this book.","url":"https://twitter.com/naval/status/942377490995015680?s=20"}
{"item_id":"5276b5e7-b8bc-4f57-b6ed-495a57bc444f","by":"Naval Ravikant","rating":"","blurb":"One of Naval Ravikant's answers to \"top 10 graphic novels?\"","url":"https://twitter.com/naval/status/693485039732916224?s=20"}
{"item_id":"a7986229-4922-4930-b5b9-137625ae44f7","by":"Naval Ravikant","rating":"","blurb":"\"Good but closer to a single-themed book.\" - Naval Ravikant","url":"https://twitter.com/naval/status/800431638261837824?s=20"}
{"item_id":"a15aa2ac-4f40-45de-ad2a-e0c60918bacf","by":"Naval Ravikant","rating":"","blurb":"Naval Ravikant tweeted about this book.","url":"https://twitter.com/naval/status/1003900342528929792?s=20"}
{"item_id":"c32fc1fd-0552-42d0-9e7b-4ca52758bf99","by":"Naval Ravikant","rating":"","blurb":"\"For historical fiction, I like [this book].\" - Naval Ravikant","url":"https://twitter.com/naval/status/247590300749541377?s=20"}
{"item_id":"c6f31b43-5684-4bb3-8d66-f69ac76b60a8","by":"Naval Ravikant","rating":"","blurb":"\"If I'm going to read fiction, might as well start at the top.\" - Naval Ravikant","url":"https://twitter.com/naval/status/699093238745997312?s=20"}
{"item_id":"045f8590-dd51-4460-b97c-259f01a0945a","by":"Bill Gates","rating":"","blurb":"I never thought much about whether I could improve my memory across a wider set of domains, but now I think I could, after reading this book.","url":"https://www.gatesnotes.com/Books/Moonwalking-with-Einstein"}
{"item_id":"ba344c04-1056-4563-b927-282e7bbc6ddd","by":"Naval Ravikant","rating":"","blurb":"\"Loved [this book] and other fiction when younger.\" - Naval Ravikant","url":"https://twitter.com/naval/status/806262424722509824?s=20"}
{"item_id":"52e0563e-87f3-4b15-b747-6f4c1b7629f7","by":"Bill Gates","rating":"","blurb":"Lost and found with “the most wondrous map ever produced”. A talented writer and doctor guides us through the past, present, and future of genome science.\n...\nThe ethical questions around genome editing are enormous. That is why I am so glad I read The Gene by Columbia University cancer doctor and researcher Siddhartha Mukherjee. I loved Mukherjee’s 2015 TED Talk and his brilliant book about cancer, The Emperor of All Maladies, which won the Pulitzer Prize in 2011. It must really tick off full-time writers that a doctor can win a Pulitzer in his spare time!\n...\nIn The Gene, Mukherjee once again shows his gift for making hard science easily accessible. He wrote this book for general audiences, because he knows that it’s not good enough for scientists alone to debate the huge ethical questions that their discoveries provoke.\n...\nMy favorite part of the book was the final section, “Post-Genome: The Genetics of Fate and Future.” It does a great job bringing into sharp focus the difficult ethical questions that will become increasingly intense.","url":"https://www.gatesnotes.com/Books/The-Gene"}
{"item_id":"ee6b09a3-2903-4fcc-8caa-c30ff3b96d36","by":"Bill Gates","rating":"","blurb":"I would say this even if I weren’t married to the author: The Moment of Lift is a terrific read.\n\nIt is a wise, honest, and beautifully written book about how empowering women lifts up everyone. (None of that will be surprising to anyone who knows Melinda.) Although it took her about a year to write, in a way she has been working on it her whole life. The Moment of Lift is about the women who have inspired Melinda, starting with her own mother, through her colleagues at Microsoft, and continuing today with the amazing scientists, farmers, educators, and leaders she meets through her work with our foundation. \n...\nBut to me, what is really impressive about the book is the way Melinda combines her mastery of data with her ability to tell powerful stories about individual women she has met.","url":"https://www.gatesnotes.com/Books/The-Moment-of-Lift"}
{"item_id":"b29b5383-f2f3-4e6d-9d35-aa0f33ea03c1","by":"Bill Gates","rating":"","blurb":"What if people run out of things to do?\nA provocative new book raises big questions about the future.\nWhat gives our lives meaning? And what if one day, whatever gives us meaning went away—what would we do then?\n\nI’m still thinking about those weighty questions after finishing Homo Deus, the provocative new book by Yuval Noah Harari.\n...\nHarari’s new book is as challenging and readable as Sapiens. Rather than looking back, as Sapiens does, it looks to the future.\n...\nHere is Harari’s most provocative idea: As good as it sounds, achieving the dream of bliss, immortality, and divinity could be bad news for the human race.\n...\nHarari does the best job I have seen of explaining the purpose problem. And he deserves credit for venturing an answer to it. He suggests that finding a new purpose requires us to develop new religion.\n...\nI wasn’t satisfied by his answer to the purpose question. But don’t let a dissatisfying conclusion dissuade you from reading Homo Deus. It is a deeply engaging book with lots of stimulating ideas and not a lot of jargon. It makes you think about the future, which is another way of saying it makes you think about the present.","url":"https://www.gatesnotes.com/Books/Homo-Deus"}
`
